### ISSUE TITLE
Masonry Column Shift layout mode

### ISSUE THREAD

**Issue by salkii** [metafizzy/isotope-docs#22]
hello
i want to ask you where is the Masonry **Column Shift layout mode** is not available on v2 we need this feature important, i don't know why you delete this feature is helpful i have a accordion filter sliding and below this filter i have some other product inside div when the filter collapsed there are still big empty space above the filter, can you help us to get this working

**Comment by desandro** [comment]
Thank you for reporting this request. See metafizzy/isotope#582
