### ISSUE TITLE
HTTPS mixed content ressource issue loading

### ISSUE THREAD

**Issue by DamChtlv** [metafizzy/isotope-docs#24]
URL : [https://isotope.metafizzy.co/v2/methods.html](https://isotope.metafizzy.co/v2/methods.html)

**Problem in the docs**

HTTPS is preventing jquery to load from google api because the link is HTTP and your "jquery.min.js" fallback doesn't work either, redirecting to a 404 page.

`Mixed Content: The page at 'https://isotope.metafizzy.co/v2/methods.html' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.
jquery.min.js Failed to load resource: the server responded with a status of 404 ()`

**Comment by desandro** [comment]
Thanks for reporting this issue. I'll be fixing this bug.

**Comment by desandro** [comment]
Fixed!
