### ISSUE TITLE
Hash / History

### ISSUE THREAD

**Issue by desandro** [metafizzy/isotope-docs#4]
missing from v2 docs. Re-do it with [native `hashchange` event](https://developer.mozilla.org/en-US/docs/Web/Events/hashchange) instead of old old jQuery BBQ

**Comment by downFast** [comment]
Any update on this? For the moment I had to combine your combo+history from V1 and use it with isotope V2 and it works fine, but I was wondering if you had any progress on this. Thanks @desandro

**Comment by desandro** [comment]
Added Filtering with URL hash example to CodePen:

http://s.codepen.io/desandro/debug/vErxXj#filter=%3Anot(.transition)

View code: http://codepen.io/desandro/pen/vErxXj

Documented in [Filtering - URL Hash](http://isotope.metafizzy.co/filtering.html#url-hash)

**Comment by downFast** [comment]
@desandro thanks! WIll this work with combination filters too?

**Comment by desandro** [comment]
Sorry, no. This was just to get something up. The same principle can be applied to combination filters. But I think I'd rather provide that comprehensive solution I mentioned earlier.
